// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLVwWka_4htyZVD5iAwCHcpGY3rTiYjts',
    appId: '1:435744974679:web:2d2c8dbe81b3974e86c012',
    messagingSenderId: '435744974679',
    projectId: 'e-care-4d678',
    authDomain: 'e-care-4d678.firebaseapp.com',
    storageBucket: 'e-care-4d678.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2nfZS5FhuENfGgfPxvg7IrpjgeZD0BQ8',
    appId: '1:435744974679:android:365a8aed855f934886c012',
    messagingSenderId: '435744974679',
    projectId: 'e-care-4d678',
    storageBucket: 'e-care-4d678.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3ThWm2bHsK-74mhAEWjAIj1BE6ojrqnc',
    appId: '1:435744974679:ios:b851433b69edc77086c012',
    messagingSenderId: '435744974679',
    projectId: 'e-care-4d678',
    storageBucket: 'e-care-4d678.firebasestorage.app',
    iosBundleId: 'com.ecare.eCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3ThWm2bHsK-74mhAEWjAIj1BE6ojrqnc',
    appId: '1:435744974679:ios:b851433b69edc77086c012',
    messagingSenderId: '435744974679',
    projectId: 'e-care-4d678',
    storageBucket: 'e-care-4d678.firebasestorage.app',
    iosBundleId: 'com.ecare.eCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLVwWka_4htyZVD5iAwCHcpGY3rTiYjts',
    appId: '1:435744974679:web:6c44a6e23485c5c286c012',
    messagingSenderId: '435744974679',
    projectId: 'e-care-4d678',
    authDomain: 'e-care-4d678.firebaseapp.com',
    storageBucket: 'e-care-4d678.firebasestorage.app',
  );

}